// Code generated by goctl. DO NOT EDIT!
// Source: m7s.proto

package m7s

import (
	"github.com/zeromicro/go-zero/zrpc"
)

type (
	M7s interface {
	}

	defaultM7s struct {
		cli zrpc.Client
	}
)

func NewM7s(cli zrpc.Client) M7s {
	return &defaultM7s{
		cli: cli,
	}
}
